name: Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [13.*, 12.*, 11.*, 10.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 11.*
            testbench: ^9.2
          - laravel: 12.*
            testbench: ^10.0
          - laravel: 13.*
            testbench: ^11.0
        exclude:
          - laravel: 10.*
            php: 8.4
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: 8.1
          - laravel: 13.*
            php: 8.1
          - laravel: 13.*
            php: 8.2

    runs-on: ${{ matrix.os }}

    name: L${{ matrix.laravel }} - ${{ matrix.stability }} - P${{ matrix.php }} - ${{ matrix.os }}

    env:
      php-extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, pcov
      key: ${{ matrix.os }}_Laravel${{ matrix.laravel }}_${{ matrix.stability }}_Php${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP extensions cache
        id: phpextcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.php-extensions }}
          key: ${{ env.key }}

      - name: "Determine composer cache directory"
        id: "composer-cache-directory"
        shell: bash
        run: "echo \"directory=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"

      - name: Cache php extensions & composer downloads
        uses: actions/cache@v4
        with:
          key: ${{ env.key }}
          path: |
            ${{ steps.phpextcache.outputs.dir }}
            ${{ steps.composer-cache-directory.outputs.directory }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.php-extensions }}
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        shell: bash
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
